### ISSUE TITLE
Develop validation methodology for developers to test against

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#12]
We need a means of validation for developers who are producing NXcansas/cansas2012 data files.

This needs to be coordinated with Nexus methodologies.

**Comment by prjemian** [comment]
At present, NeXus has no recognized validation procedure.
There is a procedure described in the manual:
http://download.nexusformat.org/doc/html/validation.html#index-0
but there is not a current working implementation.  This is the NeXus issue that best describes the situation:
https://github.com/nexusformat/definitions/issues/169

The utilities nxvalidate & NXvalidate fail for non-compliant files:
http://download.nexusformat.org/doc/html/utilities.html#index-11

Other related issues:
https://github.com/nexusformat/definitions/issues/251
https://github.com/nexusformat/definitions/issues/300
https://github.com/nexusformat/definitions/issues/382

**Comment by prjemian** [comment]
working on a project to validate NeXus files against the current definitions:
https://github.com/prjemian/punx (Python Utilities for NeXus)

**Comment by prjemian** [comment]
I will rely on the punx project for the validation requested by this issue.
