### ISSUE TITLE
Extend format to handle containing fitted data

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#15]
Item from Tokai meeting

This needs to be able to handle different types of fit and possibly also 3D bead models etc as per the bio sasCIF proposal from D Svergun at SAS2015

**Comment by toqduj** [comment]
Are you sure this is a good idea? It moves the CanSAS2012 format from a "corrected data storage container" to a "everything and the kitchen sink"-file. One would then conflate data storage aspects with analysis and reporting requirements (automatically leading to questions of whether to integrate more aspects in the same file). 

Hierarchy (or rather genealogy) also becomes a problem, if one uses f.ex. data from SANS and SAXS together for a fit. Does that mean both datasets should be included in the CanSAS file with the fit report in it? Ideally, a fit report should include the relevant datasets, not the other way around. 

Furthermore, some fitting programs' output can be rather bloaty (speaking of my own here), and would quickly render measurement files too large to handle conveniently. HDF5 has no good support for deleting entries in the file, so management of your datafile would be tricky. 

Hopefully these examples suffice to indicate that integrating fitting information inside a measurement datafile is probably not such a good idea.

**Comment by ajj** [comment]
No, I'm not sure it is a good idea. 

I suspect the best approach is for us to constrain NXcanSAS to be for reduced SAS data as originally proposed and leave domain specific data formats such as those relating to fitting to the relevant domain specialists. Now, encouraging people to develop fitted data formats that are compatible with nexus and/or hdf5 is probably a useful activity. Those of us who write analysis code should think about the best way of storing the results to enable relation of results to input data and in terms of archiving.

**Comment by prjemian** [comment]
Is this issue to be closed now?  Anything to add to the documentation?

**Comment by prjemian** [comment]
NXcanSAS is presented as a NeXus application definition for reduced data.  The NeXus standard already has a base class to describe the results from data processing or analysis: NXprocess (http://download.nexusformat.org/doc/html/classes/base_classes/NXprocess.html) and a different base class to just store a bunch of parameters: NXparameters (http://download.nexusformat.org/doc/html/classes/base_classes/NXparameters.html)

No need to extend NXcanSAS into these areas already addressed by others.
