### ISSUE TITLE
All examples are missing _indices

### ISSUE THREAD

**Issue by zjttoefs** [canSAS-org/canSAS2012#17]
Except for Q_indices and Mask_indices

There are examples with Time and Pressure and while they are defined to be written in the code the do not make it into the documentation or example files for download.

**Comment by zjttoefs** [comment]
That's one of your changes, I am afraid Pete. My old version had them on.

**Comment by zjttoefs** [comment]
Strangely the hdf5 files in the repository appear correct. But the two fakecansas.py have diverged, so the XML is incorrect, but so is the manual. That's really odd.
I'm not sure how/if that is automatically built somewhere, so I'm leaving it alone for now.

I would suggest to reconcile the two diverged fakecansas.py into one that import either an XML or HDF base class. Or ditch the XML altogether.

What stroke me as odd as well was 

  @I_axes="Time,Q"
did we not want that to be 
  @I_axes=["Time","Q"]
so you would not have to do the string parsing? 
Have we fallen back to that for the sake of XML?

@ajj ?

**Comment by zjttoefs** [comment]
Okay, I've updated the scripts and (partially) the documentation. 
It does currently not appear to auto update the web page. Could one of you have a look or point me (again?) at instructions? @prjemian @ajj

**Comment by zjttoefs** [comment]
This now builds to github.io we could close this once the cansas.org website is pointing here.

**Comment by ajj** [comment]
Updated the single link to the docs that is on the website. I see that the wiki is already fixed.
