### ISSUE TITLE
Require keeping of metadata in same file as SAS data

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#5]
Item from Tokai meeting.

**Comment by prjemian** [comment]
This is a fundamental goal of canSAS data formats.  The documentation should make this clear.

The only caveat is for HDF5 files with external file links.  When all files are accessible, these files act together as one file, a realization of this goal.

**Comment by ajj** [comment]
I think your last point speaks directly against the first. The discussion in Tokai was that while, for instance, we could make an external link to a fitted data file or to a complementary technique file (e.g. simultaneous UV spectra), the SAS data should live in the actual same file as the experimental metadata. This explicitly requires that we don't use external file links for SAS data.

**Comment by toqduj** [comment]
I agree with ajj, having links to external files means that sooner rather than later, people will not copy all necessary files leading to funny errors and crashes. SAS data should be internal.

**Comment by zjttoefs** [comment]
What is the definition of "metadata" in use here?
I would only want to duplicate a small subset of the raw data in a canSAS file.

**Comment by prjemian** [comment]
Are we agreed, then, to note in the documentation that a canSAS (reduced SAS) data file contains, without use of external file links, all information necessary?  Adding such note to NXcanSAS would resolve this issue.

**Comment by zjttoefs** [comment]
I don't think I agree with that. "All information necessary" could include the raw data and all calibration data, plus the software as well, if I had to interpret that. 

I think what we want to do here is define a standard for reduced data. So the purpose is to make reduced data available to programmes that read reduced data. SasView will not re-reduce the raw data. So anything that isn't reduced data is outside the scope of canSAS (or NXcanSAS) in my view.

It is good practise to at least include a reference to how the data was acquired and processed. Obviously.

**Comment by prjemian** [comment]
So, we have an agreement that NXcanSAS is for reduced SAS data.
A good practice/practise is to at least include a reference to how the data was acquired and processed.  Yet this is not a requirement.
External file links are not to be used for the reduced data.
There is no need for the NXcanSAS to refer to any raw data.

**Comment by prjemian** [comment]
need to resolve this for https://github.com/nexusformat/definitions/issues/420

**Comment by prjemian** [comment]
These comments will be added to the NXcanSAS documentation:

* NXcanSAS is for reduced SAS data and metadata to be stored together in one file.
* External file links are not to be used for the reduced data. 
* A good practice/practise is to at least include a reference to how the data was acquired and processed.  Yet this is not a requirement.
* There is no need for the NXcanSAS to refer to any raw data.
