### ISSUE TITLE
Rename "run" to be something else and do not require it

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#6]
Item from Tokai meeting

Currently "run" is really being used as "raw data identifier" which may not be appropriate if the SAS data are stitched from multiple runs, e.g. a 1D data set made from 3 runs at different detector distances

**Comment by prjemian** [comment]
"Run" is an optional term carried from the canSAS1d format.  It is not required.  

The use of "run" by NXcanSAS is unique in NeXus.
Other similar terms in use by NeXus are:
* "run_cycle" : NXentry, NXsubentry, NXarchive
* "run_number" : NXtofraw, NXsnshisto, NXsnsevent : http://download.nexusformat.org/doc/html/classes/contributed_definitions/NXsnshisto.html#index-12

NXcanSAS should change its use of "run" to "run-cycle" to be more consistent with other use in NeXus.

Is there a new suggested term to be added?

**Comment by ajj** [comment]
It seems to me that run_number is more in keeping with the original intent of run. Presumably run_cycle is related to source operation cycles?

I think the point is to find a term that is useful - are we using this to identify, for example, the raw data file or files from which the reduced data was obtained.

**Comment by toqduj** [comment]
Its origin probably stems from the use of run numbers in logbooks: a sequential numbering of measurements using a particular schema (I have seen a few, simple sequential numbering seems to work best). I am not sure this is needed, but we could have something in the metadata called an "external_identifier" to make such links. "run_number" would be sufficient as well, though the definition of a "run" is (as mentioned) ambiguous. 

It is probably not an important aspect of a measurement.

**Comment by prjemian** [comment]
``run_number`` is likely to be specific to some but not all facilities.
``run`` is far more general.

The original intent of ``run`` included this very debate.

**Comment by prjemian** [comment]
now I have contradicted my previous suggestion: https://github.com/canSAS-org/canSAS2012/issues/9

repeating that remark now: as stated above: 
  *NXcanSAS should change its use of ``run`` to ``run-cycle`` to be more consistent with other use in NeXus.*

If we agree this change, a note about ``run`` should appear in the documentation.

**Comment by zjttoefs** [comment]
There is probably little that could be used from that field in an automated fashion, given all the differences between facilities and the potential for aggregating data from multiple "runs" (whatever that equates to). So standardising this is not a deal breaker.

**Comment by prjemian** [comment]
so, let us leave this name as **run**
