### ISSUE TITLE
Rename or redefine @Q_uncertainty

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#7]
Item from Tokai meeting

We need to have both @Q_uncertainty - meaning the uncertainty in Q value from e.g. calibration samples and @Q_resolution which can be defined in many ways

**Comment by prjemian** [comment]
Add additional term for Q_resolution and design this implementation similar to that for uncertainty (with a "resolution" attribute of Q which indicates the dataset holding the principal resolution and an optional additional subdirectory with constituent components.

This pattern will demonstrate how to introduce further as-yet unanticipated terms related to the data.

**Comment by zjttoefs** [comment]
Consistency argument - fingers crossed for the markup to work...

We have 
I
 @uncertainty=something

For any dataset we could allow:
Q
 @resolution=qr
 @uncertainty=qu

I still have a problem how to align possible indices. For the intensity uncertainties we require a dataset of the same rank and dimensions as I. For Q resolution and uncertainty that will be overkill in most cases.

**Comment by prjemian** [comment]
need to resolve this for https://github.com/nexusformat/definitions/issues/420

**Comment by prjemian** [comment]
This attribute has been added to the definition of Q in the NXcanSAS.nxdl.xml specification:

        <attribute name="resolution" type="NX_CHAR" >
          <doc>
            (optional) 
            Generally, this is the principal resolution of each :math:`Q`.
            Names the data object (in this SASdata group) that provides the 
            :math:`Q` resolution to be used for data analysis.  Such as::
            
                @resolution="Qres"
            
            The name of the dataset containing the :math:`Q` resolution
            is flexible.  The name must be unique in the *SASdata* group.
            
            .. comment
               see: https://github.com/canSAS-org/canSAS2012/issues/7
            
               There may also be a subdirectory (optional) with constituent 
               components, similar to the handling of complex uncertainties.
            
               This pattern will demonstrate how to introduce further as-yet 
               unanticipated terms related to the data.
            -->
          </doc>
        </attribute>

See either https://github.com/nexusformat/definitions/contributed_definitions/NXcanSAS.nxdl.xml (pre-ratification location) or https://github.com/nexusformat/definitions/applications/NXcanSAS.nxdl.xml (location once NIAC ratifies this)
