### ISSUE TITLE
Generate example datasets using some real data

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#8]
Item from Tokai meeting

We need example datasets of varying complexity that demonstrate the use cases shown in the documentation. These should be standalone examples, not embedded nexus ones, so need relevant instrument and processing metadata too.

Current examples are generated with random numbers and do not have instrument metadata.

**Comment by toqduj** [comment]
Were the files generated during your beamtime compatible?

**Comment by prjemian** [comment]
Easily

**Comment by zjttoefs** [comment]
i've put the two files generated from Andrew's data into the contributed section of the examples
