### ISSUE TITLE
Cross check of keyword/entry names against nexus to check for clashes and differences in definition

### ISSUE THREAD

**Issue by ajj** [canSAS-org/canSAS2012#9]
Item from Tokai Meeting

**Comment by prjemian** [comment]
as stated in #6: NXcanSAS should change its use of "run" to "run-cycle" to be more consistent with other use in NeXus.

**Comment by prjemian** [comment]
These are the differences between the current NXcanSAS definition and the NeXus base classes

canSAS path & field                                   | NeXus path & field
----------- | --------
/SASentry/run                                         | /NXentry/run_cycle
/SASentry/SASinstrument/SAScollimation/length         | (not defined in NeXus)
/SASentry/SASinstrument/SASdetector/name              | /NXentry/NXinstrument/NXdetector/local_name
/SASentry/SASinstrument/SASdetector/SDD               | (not defined in NeXus)
/SASentry/SASinstrument/SASdetector/slit_length       | (not defined in NeXus)
/SASentry/SASinstrument/SASsource/radiation           | maps into two fields in /NXentry/NXinstrument/NXsource: type & probe
/SASentry/SASinstrument/SASsource/incident_wavelength | /NXentry/NXinstrument/NXmonochromator/wavelength


All of the SASsource/*wavelength* terms (for consistency) would be placed in the NeXus NXmonochromator base class.  Some of the *wavelength* names used by canSAS are not used or defined in NeXus.

**Comment by prjemian** [comment]
No *clashes* were found (clash: canSAS defines a name that is already in use by NeXus with a different definition).
